// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Payroll.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Payroll.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260830231820_AddPayrollItemAllowances")]
    partial class AddPayrollItemAllowances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payroll")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("ChristmasAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("christmas_allowance");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("FoodAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("food_allowance");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_salary");

                    b.Property<decimal?>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_salary");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("run_id");

                    b.Property<decimal?>("SocialSecurityContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("social_security_contribution");

                    b.Property<decimal>("TransportAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transport_allowance");

                    b.Property<decimal>("VacationAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("vacation_allowance");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("withholding_tax");

                    b.HasKey("Id")
                        .HasName("pk_payroll_item");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_payroll_item_run_id");

                    b.ToTable("payroll_item", "payroll");
                });

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollItemDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("attached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<Guid>("PayrollItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payroll_item_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_item_document");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_item_document_document_id");

                    b.HasIndex("PayrollItemId")
                        .HasDatabaseName("ix_payroll_item_document_payroll_item_id");

                    b.ToTable("payroll_item_document", "payroll");
                });

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<Guid>("OpenedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("opened_by_employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_payroll_run");

                    b.HasIndex("Year", "Month")
                        .HasDatabaseName("ix_payroll_run_year_month");

                    b.ToTable("payroll_run", "payroll");
                });

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollItem", b =>
                {
                    b.HasOne("Rivo.Payroll.Domain.PayrollRun", null)
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_item_payroll_run_run_id");
                });

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollItemDocument", b =>
                {
                    b.HasOne("Rivo.Payroll.Domain.PayrollItem", null)
                        .WithMany()
                        .HasForeignKey("PayrollItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_item_document_payroll_item_payroll_item_id");
                });

            modelBuilder.Entity("Rivo.Payroll.Domain.PayrollRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
