// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Messaging.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Messaging.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Messaging.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("closed_by_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("opened_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_open_per_customer")
                        .HasFilter("[status] = 'Open'");

                    b.ToTable("conversation", "messaging");
                });

            modelBuilder.Entity("Rivo.Messaging.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sender");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_message");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("ix_message_conversation_id_sent_at");

                    b.ToTable("message", "messaging");
                });

            modelBuilder.Entity("Rivo.Messaging.Domain.Message", b =>
                {
                    b.HasOne("Rivo.Messaging.Domain.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_conversations_conversation_id");
                });

            modelBuilder.Entity("Rivo.Messaging.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
