// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Hr.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Hr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260822220348_AddEmploymentContractAndAttendance")]
    partial class AddEmploymentContractAndAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Hr.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("checked_out_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("justification");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attendance_record");

                    b.HasIndex("Day", "Status")
                        .HasDatabaseName("ix_attendance_record_day_status");

                    b.HasIndex("EmployeeId", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_record_employee_id_day");

                    b.ToTable("attendance_record", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_department_name");

                    b.ToTable("department", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("HiredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("hired_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employee_department_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_employee_user_id");

                    b.ToTable("employee", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("attached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_document");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_document_document_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_document_employee_id");

                    b.ToTable("employee_document", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmploymentContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monthly_salary");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_employment_contract");

                    b.HasIndex("EmployeeId", "StartsOn")
                        .HasDatabaseName("ix_employment_contract_employee_id_starts_on");

                    b.ToTable("employment_contract", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("GrantsApprovalAuthority")
                        .HasColumnType("bit")
                        .HasColumnName("grants_approval_authority");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int")
                        .HasColumnName("hierarchy_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_position");

                    b.HasIndex("GrantsApprovalAuthority")
                        .HasDatabaseName("ix_position_grants_approval_authority");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_position_name");

                    b.ToTable("position", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("position_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_position_assignment");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_employee_id_effective_from");

                    b.HasIndex("PositionId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_position_id_effective_from");

                    b.ToTable("position_assignment", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeDocument", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_document_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmploymentContract", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employment_contract_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_employee_employee_id");

                    b.HasOne("Rivo.Hr.Domain.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_position_position_id");
                });
#pragma warning restore 612, 618
        }
    }
}
