// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Hr.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Hr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260831095303_UniqueEmployeeUserId")]
    partial class UniqueEmployeeUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Hr.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("checked_out_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("justification");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attendance_record");

                    b.HasIndex("Day", "Status")
                        .HasDatabaseName("ix_attendance_record_day_status");

                    b.HasIndex("EmployeeId", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_record_employee_id_day");

                    b.ToTable("attendance_record", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kind");

                    b.Property<decimal>("MonthlyValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monthly_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_benefit");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_benefit_name");

                    b.ToTable("benefit", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.BenefitEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BenefitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("benefit_id");

                    b.Property<DateOnly?>("CancelledOn")
                        .HasColumnType("date")
                        .HasColumnName("cancelled_on");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_benefit_enrolment");

                    b.HasIndex("BenefitId")
                        .HasDatabaseName("ix_benefit_enrolment_benefit_id");

                    b.HasIndex("EmployeeId", "BenefitId")
                        .HasDatabaseName("ix_benefit_enrolment_employee_id_benefit_id");

                    b.ToTable("benefit_enrolment", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date")
                        .HasColumnName("applied_on");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("HiredEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hired_employee_id");

                    b.Property<Guid>("JobOpeningId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_opening_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("stage");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_candidate");

                    b.HasIndex("HiredEmployeeId")
                        .HasDatabaseName("ix_candidate_hired_employee_id");

                    b.HasIndex("JobOpeningId", "Stage")
                        .HasDatabaseName("ix_candidate_job_opening_id_stage");

                    b.ToTable("candidate", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_department_name");

                    b.ToTable("department", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("HiredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("hired_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employee_department_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_user_id")
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("employee", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("attached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_document");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_document_document_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_document_employee_id");

                    b.ToTable("employee_document", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeLifecycleProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("LastWorkingDay")
                        .HasColumnType("date")
                        .HasColumnName("last_working_day");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_lifecycle_process");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_lifecycle_process_employee_id");

                    b.HasIndex("Kind", "Status")
                        .HasDatabaseName("ix_lifecycle_process_kind_status");

                    b.ToTable("lifecycle_process", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmploymentContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monthly_salary");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_employment_contract");

                    b.HasIndex("EmployeeId", "StartsOn")
                        .HasDatabaseName("ix_employment_contract_employee_id_starts_on");

                    b.ToTable("employment_contract", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.JobOpening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Requirements")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("requirements");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Vacancies")
                        .HasColumnType("int")
                        .HasColumnName("vacancies");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_job_opening");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_job_opening_department_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_opening_status");

                    b.ToTable("job_opening", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_leave_request");

                    b.HasIndex("EmployeeId", "StartsOn")
                        .HasDatabaseName("ix_leave_request_employee_id_starts_on");

                    b.HasIndex("Status", "ApprovalRequestId")
                        .HasDatabaseName("ix_leave_request_status_approval_request_id");

                    b.ToTable("leave_request", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.LifecycleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("completed_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_lifecycle_task");

                    b.HasIndex("ProcessId", "Order")
                        .HasDatabaseName("ix_lifecycle_task_process_id_order");

                    b.ToTable("lifecycle_task", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("GrantsApprovalAuthority")
                        .HasColumnType("bit")
                        .HasColumnName("grants_approval_authority");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int")
                        .HasColumnName("hierarchy_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_position");

                    b.HasIndex("GrantsApprovalAuthority")
                        .HasDatabaseName("ix_position_grants_approval_authority");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_position_name");

                    b.ToTable("position", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("position_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_position_assignment");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_employee_id_effective_from");

                    b.HasIndex("PositionId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_position_id_effective_from");

                    b.HasIndex("Status", "ApprovalRequestId")
                        .HasDatabaseName("ix_position_assignment_status_approval_request_id");

                    b.ToTable("position_assignment", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.BenefitEnrolment", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Benefit", null)
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_benefit_enrolment_benefit_benefit_id");

                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_benefit_enrolment_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Candidate", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.JobOpening", null)
                        .WithMany()
                        .HasForeignKey("JobOpeningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_job_opening_job_opening_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeDocument", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_document_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeLifecycleProcess", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lifecycle_process_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmploymentContract", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employment_contract_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_request_employee_employee_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.LifecycleTask", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.EmployeeLifecycleProcess", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lifecycle_task_lifecycle_process_process_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_employee_employee_id");

                    b.HasOne("Rivo.Hr.Domain.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_position_position_id");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.EmployeeLifecycleProcess", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
