// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rivo.Hr.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Hr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260811001353_InitialHr")]
    partial class InitialHr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Hr.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_department_name");

                    b.ToTable("department", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("HiredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hired_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employee_department_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_employee_user_id");

                    b.ToTable("employee", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("GrantsApprovalAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("grants_approval_authority");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("hierarchy_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_position");

                    b.HasIndex("GrantsApprovalAuthority")
                        .HasDatabaseName("ix_position_grants_approval_authority");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_position_name");

                    b.ToTable("position", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_position_assignment");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_employee_id_effective_from");

                    b.HasIndex("PositionId", "EffectiveFrom")
                        .HasDatabaseName("ix_position_assignment_position_id_effective_from");

                    b.ToTable("position_assignment", "hr");
                });

            modelBuilder.Entity("Rivo.Hr.Domain.PositionAssignment", b =>
                {
                    b.HasOne("Rivo.Hr.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_employee_employee_id");

                    b.HasOne("Rivo.Hr.Domain.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_position_position_id");
                });
#pragma warning restore 612, 618
        }
    }
}
