// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Approval.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Approval.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApprovalDbContext))]
    [Migration("20260823113220_InitialApproval")]
    partial class InitialApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("approval")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Approval.Domain.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_amount");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("minimum_amount");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("process_type");

                    b.Property<bool>("RequiresBudgetCheck")
                        .HasColumnType("bit")
                        .HasColumnName("requires_budget_check");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_policy");

                    b.HasIndex("ProcessType", "IsActive")
                        .HasDatabaseName("ix_policy_process_type_is_active");

                    b.ToTable("policy", "approval");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("AppliedPolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("applied_policy_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int")
                        .HasColumnName("current_step");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("process_type");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_employee_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_module");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("summary");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_request");

                    b.HasIndex("ProcessType", "Status")
                        .HasDatabaseName("ix_request_process_type_status");

                    b.HasIndex("SourceModule", "SourceReference")
                        .HasDatabaseName("ix_request_source_module_source_reference");

                    b.ToTable("request", "approval");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<Guid>("ApproverEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver_employee_id");

                    b.Property<bool>("HasDecided")
                        .HasColumnType("bit")
                        .HasColumnName("has_decided");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mode");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<int?>("SlaHours")
                        .HasColumnType("int")
                        .HasColumnName("sla_hours");

                    b.Property<int>("Step")
                        .HasColumnType("int")
                        .HasColumnName("step");

                    b.HasKey("Id")
                        .HasName("pk_assignment");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_assignment_approval_request_id");

                    b.HasIndex("ApproverEmployeeId", "HasDecided")
                        .HasDatabaseName("ix_assignment_approver_employee_id_has_decided");

                    b.HasIndex("RequestId", "Step")
                        .HasDatabaseName("ix_assignment_request_id_step");

                    b.ToTable("assignment", "approval");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("decided_by_employee_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<int>("Step")
                        .HasColumnType("int")
                        .HasColumnName("step");

                    b.HasKey("Id")
                        .HasName("pk_decision");

                    b.HasIndex("DecidedByEmployeeId")
                        .HasDatabaseName("ix_decision_decided_by_employee_id");

                    b.HasIndex("RequestId", "Step")
                        .HasDatabaseName("ix_decision_request_id_step");

                    b.ToTable("decision", "approval");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.PolicyStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ApproverPositionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver_position_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mode");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<int?>("SlaHours")
                        .HasColumnType("int")
                        .HasColumnName("sla_hours");

                    b.HasKey("Id")
                        .HasName("pk_policy_step");

                    b.HasIndex("ApproverPositionId")
                        .HasDatabaseName("ix_policy_step_approver_position_id");

                    b.HasIndex("PolicyId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_step_policy_id_order");

                    b.ToTable("policy_step", "approval");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.Assignment", b =>
                {
                    b.HasOne("Rivo.Approval.Domain.ApprovalRequest", null)
                        .WithMany("PendingAssignments")
                        .HasForeignKey("ApprovalRequestId")
                        .HasConstraintName("fk_assignment_request_approval_request_id");

                    b.HasOne("Rivo.Approval.Domain.ApprovalRequest", null)
                        .WithMany("Assignments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_request_request_id");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.Decision", b =>
                {
                    b.HasOne("Rivo.Approval.Domain.ApprovalRequest", null)
                        .WithMany("Decisions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decision_request_request_id");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.PolicyStep", b =>
                {
                    b.HasOne("Rivo.Approval.Domain.ApprovalPolicy", null)
                        .WithMany("Steps")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policy_step_policy_policy_id");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.ApprovalPolicy", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Rivo.Approval.Domain.ApprovalRequest", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Decisions");

                    b.Navigation("PendingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
