// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Fleet.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Fleet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260830180515_AddMaintenancePlans")]
    partial class AddMaintenancePlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int")
                        .HasColumnName("interval_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("NextDueOn")
                        .HasColumnType("date")
                        .HasColumnName("next_due_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plan");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_maintenance_plan_vehicle_id");

                    b.HasIndex("IsActive", "NextDueOn")
                        .HasDatabaseName("ix_maintenance_plan_is_active_next_due_on");

                    b.ToTable("maintenance_plan", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_record");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_maintenance_record_vehicle_id");

                    b.ToTable("maintenance_record", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("plate_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vehicle");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_plate_number");

                    b.ToTable("vehicle", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_assignment");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_vehicle_assignment_employee_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_assignment_vehicle_id");

                    b.ToTable("vehicle_assignment", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenancePlan", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Plans")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_plan_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenanceRecord", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_record_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleAssignment", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Assignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_assignment_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.Vehicle", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Maintenances");

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
