// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Fleet.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Fleet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260831055319_AddCrossSchemaDocumentForeignKey")]
    partial class AddCrossSchemaDocumentForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Fleet.Domain.FleetExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_fleet_expense");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_fleet_expense_vehicle_id");

                    b.ToTable("fleet_expense", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int")
                        .HasColumnName("interval_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("NextDueOn")
                        .HasColumnType("date")
                        .HasColumnName("next_due_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plan");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_maintenance_plan_vehicle_id");

                    b.HasIndex("IsActive", "NextDueOn")
                        .HasDatabaseName("ix_maintenance_plan_is_active_next_due_on");

                    b.ToTable("maintenance_plan", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_record");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_maintenance_record_vehicle_id");

                    b.ToTable("maintenance_record", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("plate_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vehicle");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_plate_number");

                    b.ToTable("vehicle", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_assignment");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_vehicle_assignment_employee_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_assignment_vehicle_id");

                    b.ToTable("vehicle_assignment", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("attached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_document");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_document_document_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_document_vehicle_id");

                    b.ToTable("vehicle_document", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("EndOdometer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("end_odometer");

                    b.Property<DateOnly>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("purpose");

                    b.Property<decimal>("StartOdometer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("start_odometer");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_trip");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_vehicle_trip_driver_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_trip_vehicle_id");

                    b.ToTable("vehicle_trip", "fleet");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.FleetExpense", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Expenses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fleet_expense_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenancePlan", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Plans")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_plan_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.MaintenanceRecord", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_record_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleAssignment", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Assignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_assignment_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleDocument", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_document_vehicle_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.VehicleTrip", b =>
                {
                    b.HasOne("Rivo.Fleet.Domain.Vehicle", null)
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_trip_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Rivo.Fleet.Domain.Vehicle", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Expenses");

                    b.Navigation("Maintenances");

                    b.Navigation("Plans");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
