// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Procurement.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Procurement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260827174722_RecepcaoDeMercadoria")]
    partial class RecepcaoDeMercadoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("procurement")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("DeliveryNote")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("delivery_note");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_order_id");

                    b.Property<Guid>("ReceivedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("received_by_employee_id");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_goods_receipt");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_goods_receipt_purchase_order_id");

                    b.HasIndex("ReceivedByEmployeeId")
                        .HasDatabaseName("ix_goods_receipt_received_by_employee_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_goods_receipt_status");

                    b.ToTable("goods_receipt", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("goods_receipt_id");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_order_line_id");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity_received");

                    b.HasKey("Id")
                        .HasName("pk_goods_receipt_line");

                    b.HasIndex("GoodsReceiptId")
                        .HasDatabaseName("ix_goods_receipt_line_goods_receipt_id");

                    b.HasIndex("PurchaseOrderLineId")
                        .HasDatabaseName("ix_goods_receipt_line_purchase_order_line_id");

                    b.ToTable("goods_receipt_line", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("ExpectedOn")
                        .HasColumnType("date")
                        .HasColumnName("expected_on");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requisition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order");

                    b.HasIndex("RequisitionId")
                        .HasDatabaseName("ix_purchase_order_requisition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_order_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_order_supplier_id");

                    b.ToTable("purchase_order", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_line");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_line_purchase_order_id");

                    b.ToTable("purchase_order_line", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosingReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("closing_reason");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("justification");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_employee_id");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_requisition");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_purchase_requisition_approval_request_id");

                    b.HasIndex("RequestedByEmployeeId")
                        .HasDatabaseName("ix_purchase_requisition_requested_by_employee_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_requisition_status");

                    b.ToTable("purchase_requisition", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.RequisitionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_unit_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requisition_id");

                    b.HasKey("Id")
                        .HasName("pk_requisition_line");

                    b.HasIndex("RequisitionId")
                        .HasDatabaseName("ix_requisition_line_requisition_id");

                    b.ToTable("requisition_line", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("iban");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tax_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_supplier_name");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_tax_id");

                    b.ToTable("supplier", "procurement");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.HasOne("Rivo.Procurement.Domain.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_purchase_order_purchase_order_id");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.GoodsReceiptLine", b =>
                {
                    b.HasOne("Rivo.Procurement.Domain.GoodsReceipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_line_receipts_goods_receipt_id");

                    b.HasOne("Rivo.Procurement.Domain.PurchaseOrderLine", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_line_purchase_order_line_purchase_order_line_id");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("Rivo.Procurement.Domain.PurchaseRequisition", null)
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_purchase_requisition_requisition_id");

                    b.HasOne("Rivo.Procurement.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_supplier_supplier_id");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.HasOne("Rivo.Procurement.Domain.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_line_orders_purchase_order_id");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.RequisitionLine", b =>
                {
                    b.HasOne("Rivo.Procurement.Domain.PurchaseRequisition", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requisition_line_purchase_requisition_requisition_id");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Procurement.Domain.PurchaseRequisition", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
