// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Fiscal.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Fiscal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260918011446_AddTaxEntityProfile")]
    partial class AddTaxEntityProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fiscal")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("FixedPortion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fixed_portion");

                    b.Property<decimal>("LowerBound")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("lower_bound");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("rate");

                    b.Property<Guid?>("income_tax_schedule_version_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("income_tax_schedule_version_id");

                    b.HasKey("Id")
                        .HasName("pk_income_tax_bracket");

                    b.HasIndex("income_tax_schedule_version_id")
                        .HasDatabaseName("ix_income_tax_bracket_income_tax_schedule_version_id");

                    b.ToTable("income_tax_bracket", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_income_tax_schedule");

                    b.ToTable("income_tax_schedule", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxScheduleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("LegalInstrument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_instrument");

                    b.Property<Guid?>("income_tax_schedule_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("income_tax_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_income_tax_schedule_version");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("ix_income_tax_schedule_version_effective_from");

                    b.HasIndex("income_tax_schedule_id")
                        .HasDatabaseName("ix_income_tax_schedule_version_income_tax_schedule_id");

                    b.ToTable("income_tax_schedule_version", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.SubsidyExemptionSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("kind");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_subsidy_exemption_schedule");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_subsidy_exemption_schedule_kind");

                    b.ToTable("subsidy_exemption_schedule", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.SubsidyExemptionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("LegalInstrument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_instrument");

                    b.Property<Guid?>("subsidy_exemption_schedule_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subsidy_exemption_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_subsidy_exemption_version");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("ix_subsidy_exemption_version_effective_from");

                    b.HasIndex("subsidy_exemption_schedule_id")
                        .HasDatabaseName("ix_subsidy_exemption_version_subsidy_exemption_schedule_id");

                    b.ToTable("subsidy_exemption_version", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.TaxEntityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address_detail");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("SoftwareValidationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("software_validation_number");

                    b.Property<string>("TaxRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tax_registration_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tax_entity_profile");

                    b.ToTable("tax_entity_profile", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.TaxRateSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("kind");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tax_rate_schedule");

                    b.HasIndex("Kind", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tax_rate_schedule_kind_code");

                    b.ToTable("tax_rate_schedule", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.TaxRateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("LegalInstrument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_instrument");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.Property<Guid?>("tax_rate_schedule_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tax_rate_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_rate_version");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("ix_tax_rate_version_effective_from");

                    b.HasIndex("tax_rate_schedule_id")
                        .HasDatabaseName("ix_tax_rate_version_tax_rate_schedule_id");

                    b.ToTable("tax_rate_version", "fiscal");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxBracket", b =>
                {
                    b.HasOne("Rivo.Fiscal.Domain.IncomeTaxScheduleVersion", null)
                        .WithMany("Brackets")
                        .HasForeignKey("income_tax_schedule_version_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_income_tax_bracket_income_tax_schedule_version_income_tax_schedule_version_id");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxScheduleVersion", b =>
                {
                    b.HasOne("Rivo.Fiscal.Domain.IncomeTaxSchedule", null)
                        .WithMany("Versions")
                        .HasForeignKey("income_tax_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_income_tax_schedule_version_income_tax_schedule_income_tax_schedule_id");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.SubsidyExemptionVersion", b =>
                {
                    b.HasOne("Rivo.Fiscal.Domain.SubsidyExemptionSchedule", null)
                        .WithMany("Versions")
                        .HasForeignKey("subsidy_exemption_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_subsidy_exemption_version_subsidy_exemption_schedule_subsidy_exemption_schedule_id");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.TaxRateVersion", b =>
                {
                    b.HasOne("Rivo.Fiscal.Domain.TaxRateSchedule", null)
                        .WithMany("Versions")
                        .HasForeignKey("tax_rate_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tax_rate_version_tax_rate_schedule_tax_rate_schedule_id");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxSchedule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.IncomeTaxScheduleVersion", b =>
                {
                    b.Navigation("Brackets");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.SubsidyExemptionSchedule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Rivo.Fiscal.Domain.TaxRateSchedule", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
