// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Finance.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260825140337_ExtractoDeConta")]
    partial class ExtractoDeConta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Finance.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bank");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Iban")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("iban");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bank_account");

                    b.HasIndex("Iban")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_account_iban")
                        .HasFilter("[iban] IS NOT NULL");

                    b.ToTable("bank_account", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("source_type");

                    b.HasKey("Id")
                        .HasName("pk_bank_movement");

                    b.HasIndex("BankAccountId", "OccurredAt")
                        .HasDatabaseName("ix_bank_movement_bank_account_id_occurred_at");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("ix_bank_movement_source_type_source_id")
                        .HasFilter("[source_id] IS NOT NULL");

                    b.ToTable("bank_movement", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CorrectedInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("corrected_invoice_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TaxPointDate")
                        .HasColumnType("date")
                        .HasColumnName("tax_point_date");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credit_note");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_credit_note_sales_invoice_id");

                    b.ToTable("credit_note", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("credit_note_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_credit_note_line");

                    b.HasIndex("CreditNoteId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_note_line_credit_note_id_line_number");

                    b.ToTable("credit_note_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("NextSequence")
                        .HasColumnType("int")
                        .HasColumnName("next_sequence");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document_series");

                    b.HasIndex("Type", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_document_series_type_code");

                    b.ToTable("document_series", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executed_by_employee_id");

                    b.Property<Guid?>("ExecutedFromAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executed_from_account_id");

                    b.Property<string>("ExecutedMethod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("executed_method");

                    b.Property<string>("ExecutionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("execution_reference");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_employee_id");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("supplier_invoice_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payment_request");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_payment_request_approval_request_id");

                    b.HasIndex("ExecutedByEmployeeId")
                        .HasDatabaseName("ix_payment_request_executed_by_employee_id");

                    b.HasIndex("PurchaseInvoiceId", "Status")
                        .HasDatabaseName("ix_payment_request_purchase_invoice_id_status");

                    b.ToTable("payment_request", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("supplier_invoice_number");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("SupplierTaxId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("supplier_tax_id");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_invoice");

                    b.HasIndex("DueOn")
                        .HasDatabaseName("ix_purchase_invoice_due_on");

                    b.HasIndex("SupplierTaxId", "SupplierInvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_invoice_supplier_number");

                    b.ToTable("purchase_invoice", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_receipt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_receipt_customer_id");

                    b.HasIndex("ReceivedOn")
                        .HasDatabaseName("ix_receipt_received_on");

                    b.ToTable("receipt", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.ReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("invoice_number");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("receipt_id");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_receipt_line");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_receipt_line_sales_invoice_id");

                    b.HasIndex("ReceiptId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_line_receipt_id_line_number");

                    b.ToTable("receipt_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TaxPointDate")
                        .HasColumnType("date")
                        .HasColumnName("tax_point_date");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoice_customer_id");

                    b.HasIndex("IssuedOn")
                        .HasDatabaseName("ix_sales_invoice_issued_on");

                    b.ToTable("sales_invoice", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_line");

                    b.HasIndex("SalesInvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoice_line_sales_invoice_id_line_number");

                    b.ToTable("sales_invoice_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankMovement", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.BankAccount", null)
                        .WithMany("Movements")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bank_movement_bank_account_bank_account_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("CreditNoteId");

                            b1.ToTable("credit_note", "finance");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId")
                                .HasConstraintName("fk_credit_note_credit_note_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("CreditNoteId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_credit_note_number_type_number_series_number_sequence");

                            b1.ToTable("credit_note", "finance");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId")
                                .HasConstraintName("fk_credit_note_credit_note_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNoteLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.CreditNote", null)
                        .WithMany("Lines")
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_note_line_credit_notes_credit_note_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PaymentRequest", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.PayeeParty", "Payee", b1 =>
                        {
                            b1.Property<Guid>("PaymentRequestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("payee_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("payee_tax_id");

                            b1.HasKey("PaymentRequestId");

                            b1.ToTable("payment_request", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentRequestId")
                                .HasConstraintName("fk_payment_request_payment_request_id");
                        });

                    b.Navigation("Payee")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("ReceiptId");

                            b1.ToTable("receipt", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_receipt_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("ReceiptId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_receipt_number_type_number_series_number_sequence");

                            b1.ToTable("receipt", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_receipt_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.ReceiptLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.Receipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_line_receipts_receipt_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("SalesInvoiceId");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("SalesInvoiceId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_sales_invoice_number_type_number_series_number_sequence");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_line_invoices_sales_invoice_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankAccount", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
