// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Finance.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260825191150_PostagemAutomatica")]
    partial class PostagemAutomatica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Finance.Domain.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("closed_by_employee_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reopen_reason");

                    b.Property<DateTimeOffset?>("ReopenedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reopened_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_accounting_period");

                    b.HasIndex("FiscalYear", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_accounting_period_fiscal_year_number");

                    b.ToTable("accounting_period", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bank");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Iban")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("iban");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bank_account");

                    b.HasIndex("Iban")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_account_iban")
                        .HasFilter("[iban] IS NOT NULL");

                    b.ToTable("bank_account", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("source_type");

                    b.HasKey("Id")
                        .HasName("pk_bank_movement");

                    b.HasIndex("BankAccountId", "OccurredAt")
                        .HasDatabaseName("ix_bank_movement_bank_account_id_occurred_at");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("ix_bank_movement_source_type_source_id")
                        .HasFilter("[source_id] IS NOT NULL");

                    b.ToTable("bank_movement", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("annual_total");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by_employee_id");

                    b.Property<Guid>("CostCentreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cost_centre_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_budget");

                    b.HasIndex("CostCentreId", "FiscalYear")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_cost_centre_id_fiscal_year");

                    b.ToTable("budget", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CostCentre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ResponsibleEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_employee_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cost_centre");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_centre_code");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_cost_centre_department_id")
                        .HasFilter("[department_id] IS NOT NULL");

                    b.ToTable("cost_centre", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CorrectedInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("corrected_invoice_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TaxPointDate")
                        .HasColumnType("date")
                        .HasColumnName("tax_point_date");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credit_note");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_credit_note_sales_invoice_id");

                    b.ToTable("credit_note", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("credit_note_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_credit_note_line");

                    b.HasIndex("CreditNoteId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_note_line_credit_note_id_line_number");

                    b.ToTable("credit_note_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.DepartmentCostForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<decimal>("FixedCosts")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fixed_costs");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<decimal>("OperationalCosts")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("operational_costs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cost_forecast");

                    b.HasIndex("DepartmentId", "FiscalYear", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_forecast_department_id_fiscal_year_month");

                    b.ToTable("cost_forecast", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("NextSequence")
                        .HasColumnType("int")
                        .HasColumnName("next_sequence");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document_series");

                    b.HasIndex("Type", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_document_series_type_code");

                    b.ToTable("document_series", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_journal");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_code");

                    b.ToTable("journal", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ArchivalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("archival_number");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit")
                        .HasColumnName("is_voided");

                    b.Property<string>("JournalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("journal_code");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("journal_id");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("posted_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("source_id");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_debit");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("voided_at");

                    b.HasKey("Id")
                        .HasName("pk_journal_entry");

                    b.HasIndex("JournalId")
                        .HasDatabaseName("ix_journal_entry_journal_id");

                    b.HasIndex("TransactionDate", "Period")
                        .HasDatabaseName("ix_journal_entry_transaction_date_period");

                    b.HasIndex("TransactionDate", "JournalCode", "ArchivalNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_transaction_date_journal_code_archival_number");

                    b.ToTable("journal_entry", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("parent_code");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ledger_account");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_account_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_ledger_account_parent_id");

                    b.ToTable("ledger_account", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CostCentreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cost_centre_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executed_by_employee_id");

                    b.Property<Guid?>("ExecutedFromAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executed_from_account_id");

                    b.Property<string>("ExecutedMethod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("executed_method");

                    b.Property<string>("ExecutionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("execution_reference");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_employee_id");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("supplier_invoice_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payment_request");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_payment_request_approval_request_id");

                    b.HasIndex("ExecutedByEmployeeId")
                        .HasDatabaseName("ix_payment_request_executed_by_employee_id");

                    b.HasIndex("PurchaseInvoiceId", "Status")
                        .HasDatabaseName("ix_payment_request_purchase_invoice_id_status");

                    b.HasIndex("CostCentreId", "RequestedOn", "Status")
                        .HasDatabaseName("ix_payment_request_cost_centre_id_requested_on_status")
                        .HasFilter("[cost_centre_id] IS NOT NULL");

                    b.ToTable("payment_request", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PostingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("event");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("JournalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("journal_code");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_posting_rule");

                    b.HasIndex("Event")
                        .IsUnique()
                        .HasDatabaseName("ix_posting_rule_event")
                        .HasFilter("[is_active] = 1");

                    b.ToTable("posting_rule", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("supplier_invoice_number");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("SupplierTaxId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("supplier_tax_id");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_invoice");

                    b.HasIndex("DueOn")
                        .HasDatabaseName("ix_purchase_invoice_due_on");

                    b.HasIndex("SupplierTaxId", "SupplierInvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_invoice_supplier_number");

                    b.ToTable("purchase_invoice", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_receipt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_receipt_customer_id");

                    b.HasIndex("ReceivedOn")
                        .HasDatabaseName("ix_receipt_received_on");

                    b.ToTable("receipt", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.ReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("invoice_number");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("receipt_id");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_receipt_line");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_receipt_line_sales_invoice_id");

                    b.HasIndex("ReceiptId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_line_receipt_id_line_number");

                    b.ToTable("receipt_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FiscalNotice")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fiscal_notice");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TaxPointDate")
                        .HasColumnType("date")
                        .HasColumnName("tax_point_date");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoice_customer_id");

                    b.HasIndex("IssuedOn")
                        .HasDatabaseName("ix_sales_invoice_issued_on");

                    b.ToTable("sales_invoice", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_line");

                    b.HasIndex("SalesInvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoice_line_sales_invoice_id_line_number");

                    b.ToTable("sales_invoice_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankMovement", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.BankAccount", null)
                        .WithMany("Movements")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bank_movement_bank_account_bank_account_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Budget", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.CostCentre", null)
                        .WithMany()
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budget_cost_centre_cost_centre_id");

                    b.OwnsMany("Rivo.Finance.Domain.BudgetLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("budget_id");

                            b1.Property<int>("Month")
                                .HasColumnType("int")
                                .HasColumnName("month");

                            b1.HasKey("Id")
                                .HasName("pk_budget_line");

                            b1.HasIndex("BudgetId", "Month")
                                .IsUnique()
                                .HasDatabaseName("ix_budget_line_budget_id_month");

                            b1.ToTable("budget_line", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId")
                                .HasConstraintName("fk_budget_line_budgets_budget_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("CreditNoteId");

                            b1.ToTable("credit_note", "finance");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId")
                                .HasConstraintName("fk_credit_note_credit_note_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("CreditNoteId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_credit_note_number_type_number_series_number_sequence");

                            b1.ToTable("credit_note", "finance");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId")
                                .HasConstraintName("fk_credit_note_credit_note_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNoteLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.CreditNote", null)
                        .WithMany("Lines")
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_note_line_credit_notes_credit_note_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.JournalEntry", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.Journal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_journal_journal_id");

                    b.OwnsMany("Rivo.Finance.Domain.JournalEntryLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("account_code");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("account_id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<Guid?>("CostCentreId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("cost_centre_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("description");

                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("journal_entry_id");

                            b1.Property<int>("RecordNumber")
                                .HasColumnType("int")
                                .HasColumnName("record_number");

                            b1.Property<string>("Side")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("side");

                            b1.Property<string>("SourceDocumentId")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("source_document_id");

                            b1.Property<DateTimeOffset>("SystemEntryDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("system_entry_date");

                            b1.HasKey("Id")
                                .HasName("pk_journal_entry_line");

                            b1.HasIndex("AccountId")
                                .HasDatabaseName("ix_journal_entry_line_account_id");

                            b1.HasIndex("CostCentreId")
                                .HasDatabaseName("ix_journal_entry_line_cost_centre_id")
                                .HasFilter("[cost_centre_id] IS NOT NULL");

                            b1.HasIndex("JournalEntryId", "RecordNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_journal_entry_line_journal_entry_id_record_number");

                            b1.ToTable("journal_entry_line", "finance");

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId")
                                .HasConstraintName("fk_journal_entry_line_journal_entries_journal_entry_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.LedgerAccount", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_account_ledger_account_parent_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PaymentRequest", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.PayeeParty", "Payee", b1 =>
                        {
                            b1.Property<Guid>("PaymentRequestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("payee_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("payee_tax_id");

                            b1.HasKey("PaymentRequestId");

                            b1.ToTable("payment_request", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentRequestId")
                                .HasConstraintName("fk_payment_request_payment_request_id");
                        });

                    b.Navigation("Payee")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.PostingRule", b =>
                {
                    b.OwnsMany("Rivo.Finance.Domain.PostingRuleLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("account_code");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("amount");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("description");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("int")
                                .HasColumnName("line_number");

                            b1.Property<Guid>("PostingRuleId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("posting_rule_id");

                            b1.Property<string>("Side")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("side");

                            b1.HasKey("Id")
                                .HasName("pk_posting_rule_line");

                            b1.HasIndex("PostingRuleId", "LineNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_posting_rule_line_posting_rule_id_line_number");

                            b1.ToTable("posting_rule_line", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PostingRuleId")
                                .HasConstraintName("fk_posting_rule_line_posting_rules_posting_rule_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("ReceiptId");

                            b1.ToTable("receipt", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_receipt_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("ReceiptId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_receipt_number_type_number_series_number_sequence");

                            b1.ToTable("receipt", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_receipt_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.ReceiptLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.Receipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_line_receipts_receipt_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<bool>("IsFinalConsumer")
                                .HasColumnType("bit")
                                .HasColumnName("customer_is_final_consumer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("SalesInvoiceId");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("SalesInvoiceId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_sales_invoice_number_type_number_series_number_sequence");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_line_invoices_sales_invoice_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.BankAccount", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.CreditNote", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.Receipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
