// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rivo.Finance.Infrastructure.Persistence;

#nullable disable

namespace Rivo.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rivo.Finance.Domain.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("NextSequence")
                        .HasColumnType("int")
                        .HasColumnName("next_sequence");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document_series");

                    b.HasIndex("Type", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_document_series_type_code");

                    b.ToTable("document_series", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TaxPointDate")
                        .HasColumnType("date")
                        .HasColumnName("tax_point_date");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoice_customer_id");

                    b.HasIndex("IssuedOn")
                        .HasDatabaseName("ix_sales_invoice_issued_on");

                    b.ToTable("sales_invoice", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_line");

                    b.HasIndex("SalesInvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoice_line_sales_invoice_id_line_number");

                    b.ToTable("sales_invoice_line", "finance");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.OwnsOne("Rivo.Finance.Domain.DocumentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("number_sequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("number_series");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("number_type");

                            b1.HasKey("SalesInvoiceId");

                            b1.HasIndex("Type", "Series", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ix_sales_invoice_number_type_number_series_number_sequence");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.OwnsOne("Rivo.Finance.Domain.InvoicedParty", "Customer", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AddressDetail")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("customer_address_detail");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("customer_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("customer_country");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("customer_tax_id");

                            b1.HasKey("SalesInvoiceId");

                            b1.ToTable("sales_invoice", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId")
                                .HasConstraintName("fk_sales_invoice_sales_invoice_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoiceLine", b =>
                {
                    b.HasOne("Rivo.Finance.Domain.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_line_invoices_sales_invoice_id");
                });

            modelBuilder.Entity("Rivo.Finance.Domain.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
